"""baseline: full v2.0 schema

Revision ID: 3696c0fb13e3
Revises: 
Create Date: 2026-07-23 10:31:46.682265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_time', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_table('lab_report_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_index(op.f('ix_lab_report_counters_id'), 'lab_report_counters', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('payment_proofs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portal_auth_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_auth_attempts_phone'), 'portal_auth_attempts', ['phone'], unique=False)
    op.create_table('referral_batch_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_uid', sa.String(length=50), nullable=False),
    sa.Column('test_request_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_request_id')
    )
    op.create_index(op.f('ix_referral_batch_links_batch_uid'), 'referral_batch_links', ['batch_uid'], unique=False)
    op.create_table('referral_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_uid', sa.String(length=50), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('date_received', sa.DateTime(), nullable=False),
    sa.Column('date_due', sa.DateTime(), nullable=False),
    sa.Column('courier_info', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_batches_batch_uid'), 'referral_batches', ['batch_uid'], unique=True)
    op.create_index(op.f('ix_referral_batches_referrer_id'), 'referral_batches', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_referral_batches_status'), 'referral_batches', ['status'], unique=False)
    op.create_table('referral_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_uid', sa.String(length=50), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('gross_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('net_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_ledgers_batch_uid'), 'referral_ledgers', ['batch_uid'], unique=True)
    op.create_index(op.f('ix_referral_ledgers_is_settled'), 'referral_ledgers', ['is_settled'], unique=False)
    op.create_index(op.f('ix_referral_ledgers_referrer_id'), 'referral_ledgers', ['referrer_id'], unique=False)
    op.create_table('referral_store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('facility_phone', sa.String(length=30), nullable=False),
    sa.Column('facility_address', sa.String(length=500), nullable=True),
    sa.Column('clinician_name', sa.String(length=255), nullable=True),
    sa.Column('patient_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('patient_phone_snapshot', sa.String(length=30), nullable=False),
    sa.Column('test_types_csv', sa.String(length=500), nullable=False),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_store_batch_code'), 'referral_store', ['batch_code'], unique=False)
    op.create_index(op.f('ix_referral_store_branch_id'), 'referral_store', ['branch_id'], unique=False)
    op.create_index(op.f('ix_referral_store_facility_name'), 'referral_store', ['facility_name'], unique=False)
    op.create_index(op.f('ix_referral_store_sync_id'), 'referral_store', ['sync_id'], unique=True)
    op.create_table('referrers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('organization_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('license_no', sa.String(length=100), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrers_email'), 'referrers', ['email'], unique=True)
    op.create_index(op.f('ix_referrers_phone'), 'referrers', ['phone'], unique=False)
    op.create_table('subscription_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('ai_tier', sa.Integer(), nullable=False),
    sa.Column('ai_calls_per_day', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_patients', sa.Integer(), nullable=True),
    sa.Column('blood_bank_enabled', sa.Boolean(), nullable=True),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.create_table('test_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_test_types_code')
    )
    op.create_index(op.f('ix_test_types_category'), 'test_types', ['category'], unique=False)
    op.create_index(op.f('ix_test_types_code'), 'test_types', ['code'], unique=False)
    op.create_index(op.f('ix_test_types_name'), 'test_types', ['name'], unique=False)
    op.create_index(op.f('ix_test_types_sync_id'), 'test_types', ['sync_id'], unique=True)
    op.create_table('voice_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('voice_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_announcements_branch_id'), 'voice_announcements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_voice_announcements_is_delivered'), 'voice_announcements', ['is_delivered'], unique=False)
    op.create_index(op.f('ix_voice_announcements_type'), 'voice_announcements', ['type'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('total_patients', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('abnormal_results_count', sa.Integer(), nullable=True),
    sa.Column('critical_results_count', sa.Integer(), nullable=True),
    sa.Column('top_tests', sa.JSON(), nullable=True),
    sa.Column('top_disease_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_period_start'), 'analytics_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_snapshot_type'), 'analytics_snapshots', ['snapshot_type'], unique=False)
    op.create_table('blood_donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=False),
    sa.Column('genotype', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('donation_count', sa.Integer(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('ineligibility_reason', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_donors_blood_group'), 'blood_donors', ['blood_group'], unique=False)
    op.create_index(op.f('ix_blood_donors_full_name'), 'blood_donors', ['full_name'], unique=False)
    op.create_index(op.f('ix_blood_donors_phone'), 'blood_donors', ['phone'], unique=False)
    op.create_index(op.f('ix_blood_donors_sync_id'), 'blood_donors', ['sync_id'], unique=True)
    op.create_table('disease_weekly_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('disease_tag', sa.String(length=100), nullable=False),
    sa.Column('test_category', sa.String(length=100), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('affected_patient_count', sa.Integer(), nullable=False),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('previous_week_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_weekly_trends_disease_tag'), 'disease_weekly_trends', ['disease_tag'], unique=False)
    op.create_index(op.f('ix_disease_weekly_trends_week_start'), 'disease_weekly_trends', ['week_start'], unique=False)
    op.create_index('ix_trend_week_disease', 'disease_weekly_trends', ['week_start', 'disease_tag'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('patient_no', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('age_value', sa.Integer(), nullable=True),
    sa.Column('age_unit', sa.String(length=10), nullable=True),
    sa.Column('portal_code', sa.String(length=255), nullable=True),
    sa.Column('portal_enabled', sa.Boolean(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_patient_no'), 'patients', ['patient_no'], unique=True)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index('ix_patients_phone_patient_no', 'patients', ['phone', 'patient_no'], unique=False)
    op.create_index(op.f('ix_patients_sync_id'), 'patients', ['sync_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('lab_name', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'expired', 'suspended', name='subscription_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_sync_id'), 'subscriptions', ['sync_id'], unique=True)
    op.create_table('test_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('request_no', sa.String(length=50), nullable=True),
    sa.Column('lab_number', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('test_type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'accepted', 'rejected', 'fulfilled', name='test_request_status'), server_default='pending', nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('requested_note', sa.String(length=500), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_requests_lab_number'), 'test_requests', ['lab_number'], unique=False)
    op.create_index(op.f('ix_test_requests_patient_id'), 'test_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_test_requests_request_no'), 'test_requests', ['request_no'], unique=True)
    op.create_index(op.f('ix_test_requests_status'), 'test_requests', ['status'], unique=False)
    op.create_index(op.f('ix_test_requests_sync_id'), 'test_requests', ['sync_id'], unique=True)
    op.create_index(op.f('ix_test_requests_test_result_id'), 'test_requests', ['test_result_id'], unique=False)
    op.create_index(op.f('ix_test_requests_test_type_id'), 'test_requests', ['test_type_id'], unique=False)
    op.create_table('test_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_templates_test_type_active', 'test_templates', ['test_type_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_test_templates_test_type_id'), 'test_templates', ['test_type_id'], unique=False)
    op.create_index(op.f('ix_test_templates_title'), 'test_templates', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'branch_admin', 'lab_staff', 'cashier', 'doctor', name='user_role_enum'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('blood_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=False),
    sa.Column('units_reserved', sa.Integer(), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['blood_donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_inventory_batch_no'), 'blood_inventory', ['batch_no'], unique=False)
    op.create_index(op.f('ix_blood_inventory_blood_group'), 'blood_inventory', ['blood_group'], unique=False)
    op.create_index(op.f('ix_blood_inventory_expiry_date'), 'blood_inventory', ['expiry_date'], unique=False)
    op.create_index('ix_blood_inventory_group_status', 'blood_inventory', ['blood_group', 'status'], unique=False)
    op.create_index(op.f('ix_blood_inventory_status'), 'blood_inventory', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('booking_type', sa.String(length=20), nullable=True),
    sa.Column('referrer_name', sa.String(length=255), nullable=True),
    sa.Column('referrer_phone', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_reason', sa.String(length=100), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('billing_mode', sa.String(length=20), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['referrers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.create_index(op.f('ix_bookings_email'), 'bookings', ['email'], unique=False)
    op.create_index(op.f('ix_bookings_phone'), 'bookings', ['phone'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('request_ids_csv', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('Cash', 'Transfer', 'POS', 'USSD', name='payment_method'), server_default='Cash', nullable=False),
    sa.Column('status', sa.Enum('completed', 'failed', name='payment_status'), server_default='completed', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_sync_id'), 'payments', ['sync_id'], unique=True)
    op.create_table('referral_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('bio_gender', sa.String(length=20), nullable=True),
    sa.Column('bio_dob', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('test_request_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'converted', 'rejected', name='referral_data_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['referral_store.id'], ),
    sa.ForeignKeyConstraint(['test_request_id'], ['test_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_data_sync_id'), 'referral_data', ['sync_id'], unique=True)
    op.create_table('ssdo_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('test_category', sa.String(length=100), nullable=True),
    sa.Column('disease_tags', sa.JSON(), nullable=True),
    sa.Column('severity_flag', sa.String(length=20), nullable=True),
    sa.Column('temporal_position', sa.DateTime(), nullable=True),
    sa.Column('grouped_with', sa.String(length=36), nullable=True),
    sa.Column('portal_visible', sa.Boolean(), nullable=False),
    sa.Column('ai_processed', sa.Boolean(), nullable=False),
    sa.Column('ai_summary', sa.JSON(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ssdo_category_severity', 'ssdo_index', ['test_category', 'severity_flag'], unique=False)
    op.create_index(op.f('ix_ssdo_index_ai_processed'), 'ssdo_index', ['ai_processed'], unique=False)
    op.create_index(op.f('ix_ssdo_index_patient_id'), 'ssdo_index', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ssdo_index_record_id'), 'ssdo_index', ['record_id'], unique=False)
    op.create_index(op.f('ix_ssdo_index_record_type'), 'ssdo_index', ['record_type'], unique=False)
    op.create_index(op.f('ix_ssdo_index_severity_flag'), 'ssdo_index', ['severity_flag'], unique=False)
    op.create_index(op.f('ix_ssdo_index_temporal_position'), 'ssdo_index', ['temporal_position'], unique=False)
    op.create_index(op.f('ix_ssdo_index_test_category'), 'ssdo_index', ['test_category'], unique=False)
    op.create_index('ix_ssdo_patient_type', 'ssdo_index', ['patient_id', 'record_type'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('test_type_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'pending_review', 'approved', 'released', name='resultstatus'), nullable=False),
    sa.Column('template_snapshot', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('sas_predictions', sa.JSON(), nullable=True),
    sa.Column('sas_confidence', sa.JSON(), nullable=True),
    sa.Column('sas_accepted', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['test_templates.id'], ),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_results_patient_status', 'test_results', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('ix_test_results_patient_id'), 'test_results', ['patient_id'], unique=False)
    op.create_index(op.f('ix_test_results_status'), 'test_results', ['status'], unique=False)
    op.create_index(op.f('ix_test_results_sync_id'), 'test_results', ['sync_id'], unique=True)
    op.create_index(op.f('ix_test_results_template_id'), 'test_results', ['template_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_type_id'), 'test_results', ['test_type_id'], unique=False)
    op.create_table('trial_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_identifier', sa.String(length=100), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_phone', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('test_type_id', sa.Integer(), nullable=False),
    sa.Column('test_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_items_patient_id'), 'booking_items', ['patient_id'], unique=False)
    op.create_index(op.f('ix_booking_items_patient_identifier'), 'booking_items', ['patient_identifier'], unique=False)
    op.create_table('cross_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=True),
    sa.Column('compatibility_notes', sa.String(length=500), nullable=True),
    sa.Column('performed_by', sa.String(length=120), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['blood_inventory.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_matches_patient_id'), 'cross_matches', ['patient_id'], unique=False)
    op.create_index(op.f('ix_cross_matches_sync_id'), 'cross_matches', ['sync_id'], unique=True)
    op.create_table('referral_financial_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=True),
    sa.Column('net_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_financial_records_batch_code'), 'referral_financial_records', ['batch_code'], unique=False)
    op.create_index(op.f('ix_referral_financial_records_referrer_id'), 'referral_financial_records', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_referral_financial_records_sync_id'), 'referral_financial_records', ['sync_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_financial_records_sync_id'), table_name='referral_financial_records')
    op.drop_index(op.f('ix_referral_financial_records_referrer_id'), table_name='referral_financial_records')
    op.drop_index(op.f('ix_referral_financial_records_batch_code'), table_name='referral_financial_records')
    op.drop_table('referral_financial_records')
    op.drop_index(op.f('ix_cross_matches_sync_id'), table_name='cross_matches')
    op.drop_index(op.f('ix_cross_matches_patient_id'), table_name='cross_matches')
    op.drop_table('cross_matches')
    op.drop_index(op.f('ix_booking_items_patient_identifier'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_patient_id'), table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_table('trial_records')
    op.drop_index(op.f('ix_test_results_test_type_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_template_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_sync_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_status'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_patient_id'), table_name='test_results')
    op.drop_index('ix_results_patient_status', table_name='test_results')
    op.drop_table('test_results')
    op.drop_index('ix_ssdo_patient_type', table_name='ssdo_index')
    op.drop_index(op.f('ix_ssdo_index_test_category'), table_name='ssdo_index')
    op.drop_index(op.f('ix_ssdo_index_temporal_position'), table_name='ssdo_index')
    op.drop_index(op.f('ix_ssdo_index_severity_flag'), table_name='ssdo_index')
    op.drop_index(op.f('ix_ssdo_index_record_type'), table_name='ssdo_index')
    op.drop_index(op.f('ix_ssdo_index_record_id'), table_name='ssdo_index')
    op.drop_index(op.f('ix_ssdo_index_patient_id'), table_name='ssdo_index')
    op.drop_index(op.f('ix_ssdo_index_ai_processed'), table_name='ssdo_index')
    op.drop_index('ix_ssdo_category_severity', table_name='ssdo_index')
    op.drop_table('ssdo_index')
    op.drop_index(op.f('ix_referral_data_sync_id'), table_name='referral_data')
    op.drop_table('referral_data')
    op.drop_index(op.f('ix_payments_sync_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_bookings_phone'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_email'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_blood_inventory_status'), table_name='blood_inventory')
    op.drop_index('ix_blood_inventory_group_status', table_name='blood_inventory')
    op.drop_index(op.f('ix_blood_inventory_expiry_date'), table_name='blood_inventory')
    op.drop_index(op.f('ix_blood_inventory_blood_group'), table_name='blood_inventory')
    op.drop_index(op.f('ix_blood_inventory_batch_no'), table_name='blood_inventory')
    op.drop_table('blood_inventory')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_templates_title'), table_name='test_templates')
    op.drop_index(op.f('ix_test_templates_test_type_id'), table_name='test_templates')
    op.drop_index('ix_templates_test_type_active', table_name='test_templates')
    op.drop_table('test_templates')
    op.drop_index(op.f('ix_test_requests_test_type_id'), table_name='test_requests')
    op.drop_index(op.f('ix_test_requests_test_result_id'), table_name='test_requests')
    op.drop_index(op.f('ix_test_requests_sync_id'), table_name='test_requests')
    op.drop_index(op.f('ix_test_requests_status'), table_name='test_requests')
    op.drop_index(op.f('ix_test_requests_request_no'), table_name='test_requests')
    op.drop_index(op.f('ix_test_requests_patient_id'), table_name='test_requests')
    op.drop_index(op.f('ix_test_requests_lab_number'), table_name='test_requests')
    op.drop_table('test_requests')
    op.drop_index(op.f('ix_subscriptions_sync_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_patients_sync_id'), table_name='patients')
    op.drop_index('ix_patients_phone_patient_no', table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_patient_no'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_trend_week_disease', table_name='disease_weekly_trends')
    op.drop_index(op.f('ix_disease_weekly_trends_week_start'), table_name='disease_weekly_trends')
    op.drop_index(op.f('ix_disease_weekly_trends_disease_tag'), table_name='disease_weekly_trends')
    op.drop_table('disease_weekly_trends')
    op.drop_index(op.f('ix_blood_donors_sync_id'), table_name='blood_donors')
    op.drop_index(op.f('ix_blood_donors_phone'), table_name='blood_donors')
    op.drop_index(op.f('ix_blood_donors_full_name'), table_name='blood_donors')
    op.drop_index(op.f('ix_blood_donors_blood_group'), table_name='blood_donors')
    op.drop_table('blood_donors')
    op.drop_index(op.f('ix_analytics_snapshots_snapshot_type'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_period_start'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_voice_announcements_type'), table_name='voice_announcements')
    op.drop_index(op.f('ix_voice_announcements_is_delivered'), table_name='voice_announcements')
    op.drop_index(op.f('ix_voice_announcements_branch_id'), table_name='voice_announcements')
    op.drop_table('voice_announcements')
    op.drop_index(op.f('ix_test_types_sync_id'), table_name='test_types')
    op.drop_index(op.f('ix_test_types_name'), table_name='test_types')
    op.drop_index(op.f('ix_test_types_code'), table_name='test_types')
    op.drop_index(op.f('ix_test_types_category'), table_name='test_types')
    op.drop_table('test_types')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_table('subscription_tiers')
    op.drop_index(op.f('ix_referrers_phone'), table_name='referrers')
    op.drop_index(op.f('ix_referrers_email'), table_name='referrers')
    op.drop_table('referrers')
    op.drop_index(op.f('ix_referral_store_sync_id'), table_name='referral_store')
    op.drop_index(op.f('ix_referral_store_facility_name'), table_name='referral_store')
    op.drop_index(op.f('ix_referral_store_branch_id'), table_name='referral_store')
    op.drop_index(op.f('ix_referral_store_batch_code'), table_name='referral_store')
    op.drop_table('referral_store')
    op.drop_index(op.f('ix_referral_ledgers_referrer_id'), table_name='referral_ledgers')
    op.drop_index(op.f('ix_referral_ledgers_is_settled'), table_name='referral_ledgers')
    op.drop_index(op.f('ix_referral_ledgers_batch_uid'), table_name='referral_ledgers')
    op.drop_table('referral_ledgers')
    op.drop_index(op.f('ix_referral_batches_status'), table_name='referral_batches')
    op.drop_index(op.f('ix_referral_batches_referrer_id'), table_name='referral_batches')
    op.drop_index(op.f('ix_referral_batches_batch_uid'), table_name='referral_batches')
    op.drop_table('referral_batches')
    op.drop_index(op.f('ix_referral_batch_links_batch_uid'), table_name='referral_batch_links')
    op.drop_table('referral_batch_links')
    op.drop_index(op.f('ix_portal_auth_attempts_phone'), table_name='portal_auth_attempts')
    op.drop_table('portal_auth_attempts')
    op.drop_table('payment_proofs')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_lab_report_counters_id'), table_name='lab_report_counters')
    op.drop_table('lab_report_counters')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index('ix_audit_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###