# -*- coding: utf-8 -*-
# app/models/analytics.py
from __future__ import annotations
from sqlalchemy import (
    Column, Integer, String, Date, DateTime,
    Numeric, JSON, ForeignKey, func, Index
)
from sqlalchemy.orm import relationship
from app.db.base import Base


class AnalyticsSnapshot(Base):
    """
    Aggregated lab metrics per period.
    Generated by the snapshot_service on a schedule.
    """
    __tablename__ = "analytics_snapshots"

    id = Column(Integer, primary_key=True)
    snapshot_type = Column(String(20), nullable=False, index=True)
    # daily | weekly | monthly

    period_start = Column(Date, nullable=False, index=True)
    period_end = Column(Date, nullable=False)

    branch_id = Column(Integer, ForeignKey("branches.id"), nullable=True)

    total_tests = Column(Integer, default=0)
    total_patients = Column(Integer, default=0)
    total_revenue = Column(Numeric(12, 2), default=0)
    abnormal_results_count = Column(Integer, default=0)
    critical_results_count = Column(Integer, default=0)

    top_tests = Column(JSON, nullable=True)
    # [{"code": "FBC", "name": "Full Blood Count", "count": 45}]

    top_disease_tags = Column(JSON, nullable=True)
    # [{"tag": "malaria", "count": 23}]

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

    branch = relationship("Branch")


class DiseaseWeeklyTrend(Base):
    """
    Weekly disease/virus encounter tracking.
    Powers the SAS weekly trend analysis and admin dashboard.
    """
    __tablename__ = "disease_weekly_trends"

    id = Column(Integer, primary_key=True)
    week_start = Column(Date, nullable=False, index=True)
    week_end = Column(Date, nullable=False)

    branch_id = Column(Integer, ForeignKey("branches.id"), nullable=True)

    disease_tag = Column(String(100), nullable=False, index=True)
    test_category = Column(String(100), nullable=True)

    occurrence_count = Column(Integer, default=0, nullable=False)
    critical_count = Column(Integer, default=0, nullable=False)
    affected_patient_count = Column(Integer, default=0, nullable=False)

    trend_direction = Column(String(20), nullable=True)
    # rising | falling | stable

    previous_week_count = Column(Integer, nullable=True)

    created_at = Column(DateTime, server_default=func.now())

    branch = relationship("Branch")


Index("ix_trend_week_disease", DiseaseWeeklyTrend.week_start, DiseaseWeeklyTrend.disease_tag)